call plug#begin('~/.vim/plugged')

Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'

Plug 'arcticicestudio/nord-vim'

call plug#end()

let g:airline_theme='selenized_bw'
colorscheme nord
